### PR TITLE
Add path input

### PR DESCRIPTION
**Pull request by nepp95**
Currently, premake is always put into ".premake", with no option to change this.
Made a small edit which adds an input which will change the path premake is put at.

Tested on windows, self hosted runner.

### CODE REVIEW

**Comment by abel0b** [comment]
Good !
I think it will not work as intended if the user specify an absolute path such as /tmp/premake. Could you fix it to support this special case ?
Not tested but doing just "const premakePath = core.getInput('path', { required: false })" should work ?

**Comment by nepp95** [comment]
> Good !
> 
> I think it will not work as intended if the user specify an absolute path such as /tmp/premake. Could you fix it to support this special case ?
> 
> Not tested but doing just "const premakePath = core.getInput('path', { required: false })" should work ?

I will look into that this week 😁.


`getInput()` returns the specified input just like you did with version. However, since it isn't required you MUST specify a default value to use. For backwards compatibility `.premake` sounded fine :)

**Comment by nepp95** [comment]
Well it took me a while to get round to this. In other words, I forgot.

> Not tested but doing just "const premakePath = core.getInput('path', { required: false })" should work ?

Not really. This doesn't account for the Github workspace, which is probably what you would want. I wouldn't support paths outside of the workspace, since that is something that can differ per runner. Of course, that is up to you, but I wouldn't recommend it.

> I think it will not work as intended if the user specify an absolute path such as /tmp/premake.

Following up on what I said above, I would assume this would need to be changed to a relative path + warning or just throw out an error and stop. Your choice.

**Comment by abel0b** [comment]
Ok, I would prefer throwing and error and stop then.

**Comment by abel0b** [comment]
Made a suggestion but I have not tested it. Does it look good to you ?

**Comment by nepp95** [comment]
Looks good to me!

**Pull request merged**
